/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yeucheng_jnitestdemo_MyJni */

#ifndef _Included_com_yeucheng_jnitestdemo_MyJni
#define _Included_com_yeucheng_jnitestdemo_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yeucheng_jnitestdemo_MyJni
 * Method:    getStringFromJni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yeucheng_jnitestdemo_MyJni_getStringFromJni
        (JNIEnv *env, jclass jclass1);

#ifdef __cplusplus
}
#endif
#endif
